.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "CAGET" "1" "April 17, 2006" "" ""
.SH "NAME"
caget \- read from channel access process variables
.SH "SYNOPSIS"
.B caget
.RI [ options ]
<PV name>
<PV name> ...

.SH "DESCRIPTION"
.B caget
fetches the values of one or more Channel Access (CA) Process Variables (PVs),
printing them to
R stdout .
.SH "OPTIONS"
.TP 
Format
Default output format is "name value"
.TP 
.B \-a
Wide mode "name timestamp value stat sevr" (read PVs as DBR_TIME_xxx)
.TP 
.B \-t
Terse mode \- print only value, without name
.TP 
.BI \-d " TYPE"
use the DBR type name or type code TYPE.
.TP 
.TP 
Floating point style
.TP 
.BI \-e " N"
output floating point numbers in exponential format, with N digits after the
decimal point
.TP 
.BI \-f " N"
output floating point numbers in fixed\-width format, with N digits after the
decimal point
.TP 
.BI \-g " N"
output floating point numbers in either exponential or fixed\-width format, with N digits after the decimal point
.LP 
Integer style
.TP 
.B \-0x
output integers in hexadecimal
.TP 
.B \-0o
output integers in octal
.TP 
.B \-0b
output integers in binary
.TP 
.BI \-# " N"
output only the first N elements of the PV's array
.TP 
.B \-n
Print DBF_ENUM value as number (default is enum string)
.TP 
.TP 
Channel Access options
.TP 
.BI \-w " N"
use a CA timeout of N seconds
.TP 
.B \-c
perform an asynchronous get using
\fBca_get_callback
And wait for completion

.SH "SEE ALSO"
The DBR types are fully documented in the
.I R "EPICS R3.14 Channel Access Reference Manual" ,
which is included in the
.B epics3.14\-doc
Debian package.
.SH "AUTHOR"
EPICS was collaboratively developed by Los Alamos National Laboratory, Argonne
National Laboratory, and numerous other inividuals and organizations.
.PP 
This manual page was written by Ken McIvor <mcivor@iit.edu>,
for the Debian project (but may be used by others).
