.TH PVINFO 1 "April 17, 2006"
.SH NAME
pvinfo \- display information about PVAccess process variables
.SH SYNOPSIS
.B pvinfo
.RI [ options ] " PV" ...
.SH DESCRIPTION
.B pvinfo
displays information about one or more PVAccess (PVA) Process Variables
(PVs).  It may also be used to display detailed PVA diagnostics.