.TH "PVMONITOR" "1" "April 17, 2006" "" ""
.SH "NAME"
pvmonitor \- monitor channel access process variables
.SH "SYNOPSIS"
.B pvmonitor
.RI [ options ]
<PV name>
<PV name> ...
.SH "DESCRIPTION"
.B pvmonitor
subscribes to one or more PVAccess (PVA) Process Variables (PVs), printing
their values as they change.