# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_SRC)/special

DBD += pvdbcrScalarRecord.dbd
DBD += pvdbcrScalarArrayRecord.dbd
DBD += pvdbcrAddRecord.dbd
DBD += pvdbcrRemoveRecord.dbd
DBD += pvdbcrProcessRecord.dbd
DBD += pvdbcrTraceRecord.dbd
DBD += pvdbcrAllRecords.dbd

LIBSRCS += pvdbcrScalarRecord.cpp
LIBSRCS += pvdbcrScalarArrayRecord.cpp
LIBSRCS += pvdbcrAddRecord.cpp
LIBSRCS += pvdbcrRemoveRecord.cpp
LIBSRCS += pvdbcrProcessRecord.cpp
LIBSRCS += pvdbcrTraceRecord.cpp
