
# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATABASE_TEST)/src


TESTPROD_HOST += testPlugin
testPlugin_SRCS += testPlugin.cpp
testHarness_SRCS += testPlugin.cpp
TESTS += testPlugin

TESTPROD_HOST += testPVCopy
testPVCopy_SRCS += testPVCopy.cpp
testHarness_SRCS += testPVCopy.cpp
TESTS += testPVCopy

TESTPROD_HOST += testPVRecord
testPVRecord_SRCS += testPVRecord.cpp
testHarness_SRCS += testPVRecord.cpp
TESTS += testPVRecord

TESTPROD_HOST += testExampleRecord
testExampleRecord_SRCS += testExampleRecord.cpp
testHarness_SRCS += testExampleRecord.cpp
TESTS += testExampleRecord

TESTPROD_HOST += testLocalProvider
testLocalProvider_SRCS += testLocalProvider.cpp
testHarness_SRCS += testLocalProvider.cpp
TESTS += testLocalProvider

TESTPROD_HOST += testPVAServer
testPVAServer_SRCS += testPVAServer.cpp
testHarness_SRCS += testPVAServer.cpp
TESTS += testPVAServer

TESTPROD_HOST += testChannelMonitor
testChannelMonitor_SRCS += testChannelMonitor.cpp
testHarness_SRCS += testChannelMonitor.cpp
TESTS += testChannelMonitor
