#!/bin/sh
set -e


#DEBHELPER#

if [ "$1" = "upgrade" ]
then
    if dpkg --compare-versions "$2" '<=' 3.14.11-6
    then
        # un-move configure/
        # remove the os sym-link before the "new" version is unpacked
        rm /usr/lib/epics/configure/os
        mkdir /usr/lib/epics/configure/os
        echo ">>> Customization in /etc/epics/configure will NOT be"
        echo ">>> migrated to /usr/lib/epics/configure"
    fi
fi
