usr/lib/epics/bin/linux-*
usr/lib/epics/configure
usr/lib/epics/db
usr/lib/epics/dbd
usr/lib/epics/include
usr/lib/epics/templates
usr/lib/epics/lib/linux-*/libCom*
usr/lib/epics/lib/linux-*/libca*
usr/lib/epics/lib/linux-*/libgdd*
usr/lib/epics/lib/linux-*/libcas*
usr/lib/epics/lib/host
usr/bin/makeBaseApp
usr/bin/makeBaseExt
usr/bin/softIoc
usr/share/perl5/EPICS
usr/share/epics-dev/configure
etc/epics/configure

configure/Sample.Makefile usr/lib/epics/configure

startup/EpicsHostArch usr/lib/epics/startup
startup/EpicsHostArch.pl usr/lib/epics/startup
startup/Site.profile usr/lib/epics/startup
