usr/lib/epics/bin/linux-*
usr/lib/epics/configure
usr/lib/epics/db
usr/lib/epics/dbd
usr/lib/epics/include
usr/lib/epics/templates
usr/lib/epics/lib/linux-*/libCom*
usr/lib/epics/lib/linux-*/libca*
usr/lib/epics/lib/linux-*/libgdd*
usr/lib/epics/lib/linux-*/libcas*
usr/lib/epics/lib/linux-*/libdbCore*
usr/lib/epics/lib/linux-*/libdbRecStd*
usr/lib/epics/lib/host
usr/lib/epics/lib/pkgconfig/*.pc usr/share/pkgconfig
usr/bin/ascheck
usr/bin/makeBaseApp
usr/bin/makeBaseExt
usr/bin/softIoc
usr/bin/iocLogServer
usr/bin/msi
usr/share/epics-dev/configure
etc/epics/configure
usr/lib/epics/lib/perl/DBD.pm
usr/lib/epics/lib/perl/DBD
usr/lib/epics/lib/perl/EpicsHostArch.pl

configure/Sample.Makefile usr/lib/epics/configure

startup/EpicsHostArch usr/lib/epics/startup
